// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLK3kTMKa6i2-LDANhEa6o8wbBWmMFRzo',
    appId: '1:668410325105:web:3854f77186c695215953d0',
    messagingSenderId: '668410325105',
    projectId: 'sign-language-messaging-app',
    authDomain: 'sign-language-messaging-app.firebaseapp.com',
    storageBucket: 'sign-language-messaging-app.firebasestorage.app',
    measurementId: 'G-ZYMSJRK69Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8_AOr7s8o1FrKvIZ4mB4_5iF7wokSGco',
    appId: '1:668410325105:android:66403465b90f854c5953d0',
    messagingSenderId: '668410325105',
    projectId: 'sign-language-messaging-app',
    storageBucket: 'sign-language-messaging-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYyLbJ8Atx5tNomoKO_e0PdcbpKSNIzlo',
    appId: '1:668410325105:ios:f676b7ddf32228f75953d0',
    messagingSenderId: '668410325105',
    projectId: 'sign-language-messaging-app',
    storageBucket: 'sign-language-messaging-app.firebasestorage.app',
    iosBundleId: 'com.example.signLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYyLbJ8Atx5tNomoKO_e0PdcbpKSNIzlo',
    appId: '1:668410325105:ios:f676b7ddf32228f75953d0',
    messagingSenderId: '668410325105',
    projectId: 'sign-language-messaging-app',
    storageBucket: 'sign-language-messaging-app.firebasestorage.app',
    iosBundleId: 'com.example.signLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLK3kTMKa6i2-LDANhEa6o8wbBWmMFRzo',
    appId: '1:668410325105:web:fd455f419369ea245953d0',
    messagingSenderId: '668410325105',
    projectId: 'sign-language-messaging-app',
    authDomain: 'sign-language-messaging-app.firebaseapp.com',
    storageBucket: 'sign-language-messaging-app.firebasestorage.app',
    measurementId: 'G-91B72GN13N',
  );
}
